#!/usr/bin/env python3
"""Regenerate the management reference from the validator's constants."""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from mindmap.limits import compact_guidance  # noqa: E402


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'core/skills/mindmap/references/record-limits.md'
    content = '# Record limits\n\nGenerated by `scripts/update_record_limits.py` from `src/mindmap/limits.py`.\n\n' + compact_guidance() + '\n\nNew IDs and titles must be nonblank. The graph has no lifetime concept-count limit. Canonical payload size uses sorted keys, compact separators and unescaped Unicode, after trimming the checkpoint summary. Concept field checks count Python string characters before trimming.\n'
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit('Record limit reference is stale; run scripts/update_record_limits.py')
    else:
        target.write_text(content)


if __name__ == '__main__':
    main()
